services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    restart: unless-stopped
    volumes:
      - spoolman_data:/home/app/.local/share/spoolman
    ports:
      - "7912:8000"
volumes:
  spoolman_data:
